In [2]:
import numpy as np
import pandas as pd
import cv2

np.random.seed(1212)
import keras
from keras.utils.np_utils import to_categorical
from keras.models import Model
from keras.datasets import mnist
from keras.layers import *
from keras import optimizers
from keras.layers import Input, Dense
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.utils import np_utils
from keras.utils.np_utils import to_categorical
from keras.models import model_from_json
from keras import backend as K
K.set_image_data_format('channels_last')
import tensorflow as tf


In [2]:
df_train = pd.read_csv("train.csv" , index_col = False)
df_train.head()

0    1    2    3    4    5    6    7    8    9  ...  775  776  777  778  \
0  255  255  255  255  255  255  255  255  255  255  ...    0    0    0    0   
1  255  255  255  255  255  255  255  255  255  255  ...    0    0    0    0   
2  255  255  255  255  255  255  255  255  255  255  ...    0    0    0    0   
3  255  255  255  255  255  255  255  255  255  255  ...    0    0    0    0   
4  255  255  255  255  255  255  255  255  255  255  ...    0    0    0    0   

   779  780  781  782  783  784  
0    0    0    0    0    0   10  
1    0    0    0    0    0   10  
2    0    0    0    0    0   10  
3    0    0    0    0    0   10  
4    0    0    0    0    0   10  

[5 rows x 785 columns]

In [3]:
 df_train.tail()

0    1   2  3  4  5  6  7  8  9  ...  775  776  777  778  779  780  \
157480  200  200  55  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
157481   55   55   0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
157482    0  133  58  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
157483    0    0   0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
157484    0    0   0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   

        781  782  783  784  
157480    0    0    0   13  
157481    0    0    0   13  
157482    0    0    0   13  
157483    0    0    0   13  
157484    0    0    0   13  

[5 rows x 785 columns]

In [4]:
labels = df_train[['784']]

In [5]:
df_train.drop(df_train.columns[[784]], axis = 1 , inplace = True)
df_train.head()

0    1    2    3    4    5    6    7    8    9  ...  774  775  776  777  \
0  255  255  255  255  255  255  255  255  255  255  ...    0    0    0    0   
1  255  255  255  255  255  255  255  255  255  255  ...    0    0    0    0   
2  255  255  255  255  255  255  255  255  255  255  ...    0    0    0    0   
3  255  255  255  255  255  255  255  255  255  255  ...    0    0    0    0   
4  255  255  255  255  255  255  255  255  255  255  ...    0    0    0    0   

   778  779  780  781  782  783  
0    0    0    0    0    0    0  
1    0    0    0    0    0    0  
2    0    0    0    0    0    0  
3    0    0    0    0    0    0  
4    0    0    0    0    0    0  

[5 rows x 784 columns]

In [6]:
df_train.tail()

0    1   2  3  4  5  6  7  8  9  ...  774  775  776  777  778  779  \
157480  200  200  55  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
157481   55   55   0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
157482    0  133  58  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
157483    0    0   0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   
157484    0    0   0  0  0  0  0  0  0  0  ...    0    0    0    0    0    0   

        780  781  782  783  
157480    0    0    0    0  
157481    0    0    0    0  
157482    0    0    0    0  
157483    0    0    0    0  
157484    0    0    0    0  

[5 rows x 784 columns]

In [7]:
labels = np.array(labels)

In [8]:
cat = to_categorical(labels, num_classes=20)
print(cat)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [9]:
arr = []
for i in range(157485):
    arr.append(np.array(df_train[i : i+1]).reshape(28,28,1))

In [10]:
np.random.seed(7)

In [11]:
model = Sequential()
model.add(Conv2D(30, (5, 5), input_shape=(28, 28, 1), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(15, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(20, activation='softmax'))

# Compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 24, 24, 30)        780       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 12, 12, 30)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 10, 10, 15)        4065      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 15)         0         
 2D)                                                             
                                                                 
 dropout (Dropout)           (None, 5, 5, 15)          0         
                                                                 
 flatten (Flatten)           (None, 375)               0

In [12]:
model.fit(np.array(arr), cat, epochs=5,batch_size = 5, shuffle=True,verbose=1)

Epoch 1/5
31497/31497 [==============================] - 78s 2ms/step - loss: 0.2429 - accuracy: 0.9372
Epoch 2/5
31497/31497 [==============================] - 74s 2ms/step - loss: 0.1356 - accuracy: 0.9671
Epoch 3/5
31497/31497 [==============================] - 73s 2ms/step - loss: 0.1204 - accuracy: 0.9715
Epoch 4/5
31497/31497 [==============================] - 72s 2ms/step - loss: 0.1177 - accuracy: 0.9725
Epoch 5/5
31497/31497 [==============================] - 71s 2ms/step - loss: 0.1143 - accuracy: 0.9745


In [13]:
model_json = model.to_json()
with open("model_json.json", "w") as json_file:
    json_file.write(model_json)
    
# serialize weights to HDF5
model.save_weights("model_json.h5")

In [3]:
img = cv2.imread('C:\\Users\\Narendra\\Desktop\\test.png')
cv2.imshow("temp",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
if img is not None:
    img = ~img
    greyImg = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    ret,thresh=cv2.threshold(greyImg,127,255,cv2.THRESH_BINARY)
    ctrs,hie=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
    cnt=sorted(ctrs, key=lambda ctr: cv2.boundingRect(ctr)[0])
    w=int(28)
    h=int(28)
    train_data=[]
    rects=[]
    for c in cnt :
        x,y,w,h= cv2.boundingRect(c)
        rect=[x,y,w,h]
        rects.append(rect)
    bool_rect=[]
    for r in rects:
        l=[]
        for rec in rects:
            flag=0
            if rec!=r:
                if r[0]<(rec[0]+rec[2]+10) and rec[0]<(r[0]+r[2]+10) and r[1]<(rec[1]+rec[3]+10) and rec[1]<(r[1]+r[3]+10):
                    flag=1
                l.append(flag)
            if rec==r:
                l.append(0)
        bool_rect.append(l)
    dump_rect=[]
    for i in range(0,len(cnt)):
        for j in range(0,len(cnt)):
            if bool_rect[i][j]==1:
                area1=rects[i][2]*rects[i][3]
                area2=rects[j][2]*rects[j][3]
                if(area1==min(area1,area2)):
                    dump_rect.append(rects[i])
    final_rect=[i for i in rects if i not in dump_rect]
    for r in final_rect:
        x=r[0]
        y=r[1]
        w=r[2]
        h=r[3]
        im_crop =thresh[y:y+h+10,x:x+w+10]
        

        im_resize = cv2.resize(im_crop,(28,28))
        cv2.imshow("work",im_resize)
        cv2.waitKey(0)
        cv2.destroyAllWindows()

        im_resize=np.reshape(im_resize,(1,28,28))
        train_data.append(im_resize)

In [6]:
s=''
for i in range(len(train_data)):
    train_data[i]=np.array(train_data[i])
    train_data[i]=train_data[i].reshape(1,28,28,1)
    result= np.argmax(model.predict(train_data[i]), axis = 1)
    if(result[0]==0):
        s=s+'0'
    if(result[0]==1):
        s=s+'1'
    if(result[0]==2):
        s=s+'2'
    if(result[0]==3):
        s=s+'3'
    if(result[0]==4):
        s=s+'4'
    if(result[0]==5):
        s=s+'5'
    if(result[0]==6):
        s=s+'6'
    if(result[0]==7):
        s=s+'7'
    if(result[0]==8):
        s=s+'8'
    if(result[0]==9):
        s=s+'9'
    if(result[0]==10):
        s=s+'-'
    if(result[0]==11):
        s=s+'+'
    if(result[0]==12):
        s=s+'/'
    if(result[0]==13):
        s=s+'*'  
    
print(s) 
eval(s)
 

NameError: name 'model' is not defined

In [5]:
eval(s)

NameError: name 's' is not defined